version: "3.3"

services:
    # Database
    db:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            # Will Change Later
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - wpsite
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - "7065:80"
        networks:
            - wpsite
        environment:
            MYSQL_ROOT_PASSWORD: password
    wordpress:
        depends_on:
            - db
        image: wordpress:php8.2-apache
        ports:
            - '8886:80'
        restart: always
        volumes: ['./:/var/www/html']
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        extra_hosts:
            - "localhost:172.18.0.1"
        networks:
            - wpsite
networks:
    wpsite:
volumes:
    db_data:
